config/routes.rb
Rails.application.routes.draw do
  root "profiles#index"
  resources :profiles
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: "registrations",
    passwords: "password"
  }
  # adding custom urls in devise controller
  devise_scope :user do
    post "/user/check_availability/email",
         to:  "registrations#check_email_availability"
    get "user/signup", to:  "registrations#new"
    get "user/password/", to: "password#new", as: "forgot_password"
  end
  get "/stream", to: "profiles#live_streaming"
  get "admins/users", to: "admins#list"
  get "/admins/add_members", to: redirect("/admins/new")
  match "/admins/role_userole" => "admins#users", via: [:get, :post]
  match "/role_userole" => "admins#users", via: [:get, :post]
  resources :users
  resources :posts
  resources :admins
  post "check/to_delete_id/" => "admins#remove"
  post "admins/add_members" => "admins#add_members"
  get "/about_us/" => "aboutus#about_us"
  get "/contact_us" => "aboutus#contact_us"
  post "/profiles/user/role/:id" => "profiles#get_role"
  match "/admin_assign_roles" => "admins#admin_assign_roles", via: [:get, :post]
  match "/update" => "admins#bulk_user_update", via: [:post, :get]
  # You can have the root of your site routed with "root"
  # atch "/profiles/update/profile/pic" =>
  # profiles#update_profile_pic", via: [:get, :post], defaults: { format: "js" }
  patch "/update_profile_image", to: "profiles#update_profile_image"
  get "/", to: "profiles#index"
  get "/admins/add_members", to: "admins#add_members"
  post "/profiles/getuser/image", to: "profiles#fb_image"
  post "/notifications", to: "notifications#send_notifications"
  get "/message/:id", to: "profiles#message"
  get "/chatroom", to: "notifications#chat"
  post "/post_chat", to: "profiles#send_chat"
  get "/getnotifications", to: "notifications#display_notification"
  # dynamic routing for api
  get "/apis", to: "apis/welcome#index"
  post ":controller(/:action(/*params))", controller: /apis\/[^\/]+/
  get ":controller(/:action(/*params))", controller: /apis\/[^\/]+/
  put ":controller(/:action(/*params))", controller: /apis\/[^\/]+/
  patch ":controller(/:action(/*params))", controller: /apis\/[^\/]+/
  delete ":controller(/:action(/*params))", controller: /apis\/[^\/]+/
end

app/models/profile.rb
# Talentica - bootstrap project
# Copyright   Ashwini Kumar
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
class Profile < ActiveRecord::Base
  extend Utils::OauthImage
  belongs_to :user
  def self.user_fb_image(user)
    info = UserAuthentication
           .where("authentication_provider_id= 1 and user_id= ?", user.id)
           .first
    if info
      uri = "https://graph.facebook.com/v2.5/#{info.uid}/picture?type=large&redirect=false"
      facebook_api(uri, user)
      user.update_attribute(:avatar_file_name, "img.jpg")
      user
    else
      {
        message: "User need to be logged-in via fabebook"
      }
    end
  end
end

app/controllers/profiles_controller.rb
# Talentica - bootstrap project
# Copyright   Ashwini Kumar
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
class ProfilesController < ApplicationController
  # include ActionController::Live
  include Utils::OauthImage
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!
  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = current_user
    cookies[:user] = @profiles.id
  end

  # GET /profiles/1
  # GET /profiles/1.json

  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  def update_profile_image
    debugger
    id = params[:user][:attr].to_i
    user = User.find(id)
    attribute = { avatar: params[:user][:avatar] }
    @response = user.update_attributes(attribute)
    render json: {
      user: user.id,
      flag: @response,
      error: user.errors.full_messages,
      img: user.avatar_file_name
    }
  end
  # POST /profiles
  # POST /profiles.json

  def create
    @profile = Profile.new(profile_params)
    respond_to do |format|
      if @profile.save
        format.html do
          redirect_to @profile, notice:
          "Profile was successfully created."
        end
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json do
          render json: @profile.errors,
                 status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html do
          redirect_to @profile,
                      notice: "Profile was successfully updated."
        end
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json do
          render json: @profile.errors,
                 status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html do
        redirect_to profiles_url, notice:
                                 "Profile was successfully destroyed."
      end
      format.json { head :no_content }
    end
  end

  def fb_image
    @response = Profile.user_fb_image current_user if current_user
    render json: {
      user: @response.id,
      img: "img.jpg"
    }
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_profile
    @profile = Profile.find_by_id(params[:id])
    @user = User.find_by_id(@profile.user_id)
  end

  # Never trust parameters from the scary internet,
  # only allow the white list through.
  def profile_params
    params.require(:profile).permit(:fname, :lname)
  end
end

app/helpers/profiles_helper.rb
# Talentica - bootstrap project
# Copyright   Ashwini Kumar
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
module ProfilesHelper
  def display_user_roles(user)
    s = []
    user.roles.each do |r|
      s << r["user_role"]
    end
    get_roles_name s
  end
end

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fname %><br>
    <%= f.text_field :fname %>
  </div>
  <div class="field">
    <%= f.label :lname %><br>
    <%= f.text_field :lname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>
<br>
<div class = "mul_chat">
<%#= react_component('Profile',{ firstname: @profiles.firstname, lastname: @profiles.lastname },
    html_options = { prerender: true }) %>
</div>

app/views/profiles/message.js.erb
<%# broadcast "/message/227" do %>
// $("#message_display").append("<br/><span class='m_chat'><%#=@message%></span><br/>"); 
//$("#message_post").val("")
<%# end %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>
<div class = "user-details" >
</div>

<%= form_for @user, 
             url: { action: 'update_profile_image' },
             remote:true, authenticity_token: true do |f| %>
 <input type = 'hidden' name = 'user[attr]' value = "<%=@user.id%>" />
<div class ="user-med-pic">
     <%= image_tag current_user.avatar.url(:medium), id: 'dis-img' %>
    <a id="change-picture" >Update profile picture</a>
   </div>

    <div style = "display:none" id = "update_pic" >
    <%= render partial: 'devise/registrations/image_upload' , locals: { f: f } %>
    <input type = "button" value ="Update" id= "update-img" 
      onclick ="AjaxUpdateImage($('form').attr('action'), $('form').attr('id'))" /><br>
     <button type="button" class ="fb_up_pic" id = "fb_up" >Use my facebook image</button> 
    </div>
<% end %>