config/routes.rb
Rails.application.routes.draw do
  root "profiles#index"
  resources :profiles
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: "registrations",
    passwords: "password"
  }
  # adding custom urls in devise controller
  devise_scope :user do
    post "/user/check_availability/email",
         to:  "registrations#check_email_availability"
    get "user/signup", to:  "registrations#new"
    get "user/password/", to: "password#new", as: "forgot_password"
  end
  get "/stream", to: "profiles#live_streaming"
  get "admins/users", to: "admins#list"
  get "/admins/add_members", to: redirect("/admins/new")
  match "/admins/role_userole" => "admins#users", via: [:get, :post]
  match "/role_userole" => "admins#users", via: [:get, :post]
  resources :users
  resources :posts
  resources :admins
  post "check/to_delete_id/" => "admins#remove"
  post "admins/add_members" => "admins#add_members"
  get "/about_us/" => "aboutus#about_us"
  get "/contact_us" => "aboutus#contact_us"
  post "/profiles/user/role/:id" => "profiles#get_role"
  match "/admin_assign_roles" => "admins#admin_assign_roles", via: [:get, :post]
  match "/update" => "admins#bulk_user_update", via: [:post, :get]
  # You can have the root of your site routed with "root"
  # atch "/profiles/update/profile/pic" =>
  # profiles#update_profile_pic", via: [:get, :post], defaults: { format: "js" }
  patch "/update_profile_image", to: "profiles#update_profile_image"
  get "/", to: "profiles#index"
  get "/admins/add_members", to: "admins#add_members"
  post "/profiles/getuser/image", to: "profiles#fb_image"
  post "/notifications", to: "notifications#send_notifications"
  get "/message/:id", to: "profiles#message"
  get "/chatroom", to: "notifications#chat"
  post "/post_chat", to: "profiles#send_chat"
  get "/getnotifications", to: "notifications#display_notification"
  # dynamic routing for api
  get "/apis", to: "apis/welcome#index"
  post ":controller(/:action(/*params))", controller: /apis\/[^\/]+/
  get ":controller(/:action(/*params))", controller: /apis\/[^\/]+/
  put ":controller(/:action(/*params))", controller: /apis\/[^\/]+/
  patch ":controller(/:action(/*params))", controller: /apis\/[^\/]+/
  delete ":controller(/:action(/*params))", controller: /apis\/[^\/]+/
end

app/views/admins/_form.html.erb
<%= form_for @user , :url => url_for(:controller => 'admins', :action => 'add_members'),
   html: { class: "admin-add-member" }  do |f| %>
<% if  !@response.nil? &&  !@response.errors.full_messages.empty? %>
<%= @response.errors.full_messages %><br>
<% end %>
<%= flash[:success] %><br>
  First name: <%= f.text_field :firstname, class: "form-control"%><br />
  Last name : <%= f.text_field :lastname, class: "form-control" %><br />
  Email :     <%= f.text_field :email, class: "form-control" %><br />

<%= render 'roles' %>
  <%= f.submit class: "btn btn-default"%>
<% end %>

app/views/admins/_roles.html.erb
<br>
Assign Role:<br />
<div>
     <% display_roles.each do |p| %>
      <input type="checkbox"  value=<%=p.id%> name =roles[] class = "checkbox-inline"> <%= p.name %> <br>
   <% end %>

</div>

app/views/admins/add_members.html.erb
<%= render "form" %>

app/views/admins/index.html.erb
<h3 id = "admin-header">Administration</h1>
<%= link_to 'Members' , :controller => 'admins', :action => 'list' %><br>
<%= link_to 'Add Members' , admins_add_members_path %>
 <%= text_field(:role, :userole, class: "admin-add-member-role" ,:placeholder => "search members") %>

 <%= form_tag ("/admin_assign_roles") do %>
 <div id ="data-set" class = "suggestion-data" > </div>
 <div id ="role" class = "suggestion-role" > <%= render 'roles' %></div>
 <input type ="submit" value ="assign roles" class = "sub-roles" />
<% end %>

<%= javascript_tag  do -%>
 $( "#role_userole" ).keypress(function(e) {
    if (e.which != 13 ){
    ForaAotucompleteFiled(this.id)
    }
  });
<% end %>

app/views/admins/list.html.erb
<%= form_tag("/update", method: "post", id: "user-edit" ) do %>
<table  >
<% @users.each do |m| %>
<tr id = "<%=m.id%>" class ="usero" > 
  <td> <input  type = 'text' value = <%=m.firstname%> name = "userori[<%=m.id%>[firstname]]"  readonly=""  ></td>
  <td> <input type = 'text' value = <%=m.lastname%> name = "userori[<%=m.id%>[lastname]]" readonly="" > </td>
  <td><input type = 'text' value =  <%=m.email%> name = "userori[<%=m.id%>[email]]" readonly="" email = <%=m.email%>></td>
  <td> <button type="button" class = "del-usr btn-link" value = "<%=m.email%>" > Delete</button> </td>
 </tr>

<tr id = "usere-<%=m.id%>" class ="usere" > 
 <td> <input  type = 'text' value = <%=m.firstname%> name = "userchg[<%=m.id%>[firstname]]" ></td>
 <td> <input type = 'text' value = <%=m.lastname%> name = "userchg[<%=m.id%>[lastname]]" > </td> 
 <td><input type = 'text' value =  <%=m.email%> name = "userchg[<%=m.id%>[email]]" ></td></tr>
<% end %>
</table>
<%= submit_tag("Update", :id =>'update-usr' ) %>
 <button type="button"  onclick = "EditUser()" id= "userebuton" > Edit</button>
<% end %>

app/views/admins/new.html.erb
 <%= render 'form' %> 