config/routes.rb
Rails.application.routes.draw do
  root "profiles#index"
  resources :profiles
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: "registrations",
    passwords: "password"
  }
  # adding custom urls in devise controller
  devise_scope :user do
    post "/user/check_availability/email",
         to:  "registrations#check_email_availability"
    get "user/signup", to:  "registrations#new"
    get "user/password/", to: "password#new", as: "forgot_password"
  end
  get "/stream", to: "profiles#live_streaming"
  get "admins/users", to: "admins#list"
  get "/admins/add_members", to: redirect("/admins/new")
  match "/admins/role_userole" => "admins#users", via: [:get, :post]
  match "/role_userole" => "admins#users", via: [:get, :post]
  resources :users
  resources :posts
  resources :admins
  post "check/to_delete_id/" => "admins#remove"
  post "admins/add_members" => "admins#add_members"
  get "/about_us/" => "aboutus#about_us"
  get "/contact_us" => "aboutus#contact_us"
  post "/profiles/user/role/:id" => "profiles#get_role"
  match "/admin_assign_roles" => "admins#admin_assign_roles", via: [:get, :post]
  match "/update" => "admins#bulk_user_update", via: [:post, :get]
  # You can have the root of your site routed with "root"
  # atch "/profiles/update/profile/pic" =>
  # profiles#update_profile_pic", via: [:get, :post], defaults: { format: "js" }
  patch "/update_profile_image", to: "profiles#update_profile_image"
  get "/", to: "profiles#index"
  get "/admins/add_members", to: "admins#add_members"
  post "/profiles/getuser/image", to: "profiles#fb_image"
  post "/notifications", to: "notifications#send_notifications"
  get "/message/:id", to: "profiles#message"
  get "/chatroom", to: "notifications#chat"
  post "/post_chat", to: "profiles#send_chat"
  get "/getnotifications", to: "notifications#display_notification"
  # dynamic routing for api
  get "/apis", to: "apis/welcome#index"
  post ":controller(/:action(/*params))", controller: /apis\/[^\/]+/
  get ":controller(/:action(/*params))", controller: /apis\/[^\/]+/
  put ":controller(/:action(/*params))", controller: /apis\/[^\/]+/
  patch ":controller(/:action(/*params))", controller: /apis\/[^\/]+/
  delete ":controller(/:action(/*params))", controller: /apis\/[^\/]+/
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Talen" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application", "http://localhost:9292/faye.js" %>
     <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>
     <script src="http://cdn.jsdelivr.net/jquery.validation/1.15.0/additional-methods.min.js"></script>
     <%= stylesheet_link_tag  'jquery' %>
    <%#= javascript_include_tag 'http://code.jquery.com/jquery-1.10.2.js' %> <!-- causing issue in push notification-->
   <%= javascript_include_tag 'http://code.jquery.com/ui/1.11.4/jquery-ui.js' %>
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Talen</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
             <% if current_user && current_user.admin %>
              <li><%= link_to 'Adminstration', :controller => 'admins', :action => 'index' %></li>
             <% end %>
              <% if current_user %> 
                <li class="dropdown">
                  <a data-toggle="dropdown" class="dropdown-toggle" href="#">More Options<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                      <li><%= link_to 'Edit Profile', edit_profile_path(current_user.profile.id) %></li>
                      <li><%= link_to "Edit Account", edit_user_registration_path(:id => current_user.id) %></li>
                      <li><%= link_to "Sign Out" , destroy_user_session_path , :method => 'delete'%></li>                    
                    </ul>
                </li>                 
                <li><a href="/about_us">About Us</a></li>
                <li> <a href="/contact_us">Contcat us</a></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Send Request</a>
                    <ul class="dropdown-menu ss">
                       <% users.each do |f| %>
                         <li class = "notify"> <a channel ="/notification/<%=f.id %>"><%=f.firstname %> <%= f.lastname %></a> </li>
                       <% end %>                  
                    </ul>
                </li>
                <li class = "header-profile"> 
                  <a href = "<%= profile_path(:id => current_user.profile.id) %>" class = "user-thumb-name">
                    <% @notifications = show_unread_notification(current_user.id) 
                      display = @notifications > 0 ? "bubble" : "bubble hide "
                     %>
                   <div class = "<%=display%>"><%=@notifications %></div>
                     <img class="user-thumb t" src = "/images/notification.jpg" >
                     <span class ="user-thumb-span" >Hi <%=current_user.firstname %></span>
                   <div class ="header-img"><%= image_tag current_user.avatar.url(:thumb), class: 'user-thumb' %></div>
                 </a>
               </li>
              </ul>
            </div>
          </div>
        </div>
    <div class="chat-list"> 
    <% users.each do |f| %>
      <li class = "messlist"> <a channel ="/message/<%=f.id %>" class ="cl" ><%=f.firstname %> <%= f.lastname %></a> </li>
      <% end %>
    </div>
   <% end %>
    <% if controller_name == "sessions" || controller_name == "registrations" 
       css_signup = "sinup"; else  css_signup = "" ; end %>
    <div class="container ined <%=css_signup%>">
      <div class="row">
      <% if controller_name != "admins"  && false %>
     <div class="input-group">
              <input type="text" class="form-control srch-term" placeholder="Search" name="srch-term" id="srch-term">
          </div>
      <% end %>
        <div class="col-lg-9">
          <%#= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
        </div><!--/span-->
      </div><!--/row-->
    </div> <!-- /container -->
   <div class = "foot">
   </div>
  </body>
</html>